ALTER TABLE couples ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE moods ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE notification_preferences ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
