ALTER TABLE memories ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE diaries ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE anniversaries ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
